AriaSoleh.Co/ServiceHost/Areas/Administration/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ServiceHost.Areas.Administration.Pages
{
    public class IndexModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

AriaSoleh.Co/ServiceHost/Areas/Administration/Pages/Shop/CompanyProjects/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ShopManagement.Application.Contracts.CompanyProject;

namespace ServiceHost.Areas.Administration.Pages.Shop.CompanyProjects
{
    public class IndexModel : PageModel
    {
        public CompanyProjectSearchModel SearchModel;
        public List<CompanyProjectViewModel> CompanyProjects;
        private readonly ICompanyProjectApplication _companyProject;

        public IndexModel(ICompanyProjectApplication companyProject)
        {
            _companyProject = companyProject;
        }

        public void OnGet(CompanyProjectSearchModel searchModel)
        {
            CompanyProjects = _companyProject.Search(searchModel);
        }

        public IActionResult OnGetCreate()
        {
            return Partial("./Create", new CreateCompanyProject());
        }
        public JsonResult OnPostCreate(CreateCompanyProject command)
        {
            var result = _companyProject.Create(command);
            return new JsonResult(result);
        }

        public IActionResult OnGetEdit(Guid id)
        {
            var model = _companyProject.GetDetails(id);
            return Partial("./Edit", model);
        }
        public JsonResult OnPostEdit(EditCompanyProject command)
        {
            var result = _companyProject.Edit(command);
            return new JsonResult(result);
        }
    }
}

AriaSoleh.Co/ServiceHost/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace ServiceHost.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

AriaSoleh.Co/ServiceHost/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ServiceHost.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

AriaSoleh.Co/ServiceHost/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ServiceHost.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

AriaSoleh.Co/ServiceHost/ViewComponents/CompanyProjectViewComponent.cs
using _01_Query.Contracts.CompanyProject;
using Microsoft.AspNetCore.Mvc;

namespace ServiceHost.ViewComponents
{
    public class CompanyProjectViewComponent : ViewComponent
    {
        private readonly ICompanyProjectQuery _projectQuery;

        public CompanyProjectViewComponent(ICompanyProjectQuery projectQuery)
        {
            _projectQuery = projectQuery;
        }

        public IViewComponentResult Invoke()
        {
            var projects = _projectQuery.GetProjects();
            return View(projects);
        }
    }
}

AriaSoleh.Co/ServiceHost/Areas/Administration/Pages/Shop/CompanyProjects/Create.cshtml
@model ShopManagement.Application.Contracts.CompanyProject.CreateCompanyProject
@{
}

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h4 class="modal-title">ایجاد پروژه جدید
    </h4>
</div>

<form asp-page="./Index" asp-page-handler="Create"
      method="post"
      data-ajax="true"
      data-callback=""
      data-action="Refresh"
      enctype="multipart/form-data">
    <div class="modal-body">
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="Name" class="control-label">نام</label>
                    <input type="text" class="form-control" asp-for="Name" onchange="makeSlug('Name', 'Slug')">
                    <span asp-validation-for="Name" class="error"></span>
                </div>
            </div><div class="col-md-6"> 
                <div class="form-group">
                    <label asp-for="Slug" class="control-label">اسلاگ</label>
                    <input type="text" class="form-control" asp-for="Slug">
                    <span asp-validation-for="Slug" class="error"></span>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <label asp-for="Picture" class="control-label">عکس</label>
                    <input type="text" class="form-control" asp-for="Picture">
                    <span asp-validation-for="Picture" class="error"></span>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="PictureAlt" class="control-label">Alt</label>
                    <input type="text" class="form-control" asp-for="PictureAlt">
                    <span asp-validation-for="PictureAlt" class="error"></span>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="PictureTitle" class="control-label">عنوان عکس</label>
                    <input type="text" class="form-control" asp-for="PictureTitle">
                    <span asp-validation-for="PictureTitle" class="error"></span>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="form-group no-margin">
                    <label asp-for="Description" class="control-label">توضیحات</label>
                    <textarea class="form-control autogrow" asp-for="Description" onchange="fillField('Description', 'MetaDescription')"
                              style="overflow: hidden; word-wrap: break-word; resize: horizontal; height: 104px;"></textarea>
                    <span asp-validation-for="Description" class="error"></span>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <label asp-for="Keywords" class="control-label">کلمات کلیدی</label>
                    <input type="text" class="form-control" asp-for="Keywords">
                    <span asp-validation-for="Keywords" class="error"></span>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="form-group no-margin">
                    <label asp-for="MetaDescription" class="control-label">توضیحات متا</label>
                    <textarea class="form-control autogrow" asp-for="MetaDescription"
                              style="overflow: hidden; word-wrap: break-word; resize: horizontal; height: 104px;"></textarea>
                    <span asp-validation-for="MetaDescription" class="error"></span>
                </div>
            </div>
        </div>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default waves-effect" data-dismiss="modal">بستن</button>
        <button type="submit" class="btn btn-info waves-effect waves-light">ایجاد</button>
    </div>
</form>

AriaSoleh.Co/ServiceHost/Areas/Administration/Pages/Shop/CompanyProjects/Edit.cshtml
@model ShopManagement.Application.Contracts.CompanyProject.EditCompanyProject
@{
}

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h4 class="modal-title">ویرایش پروژه: @Model.Name</h4>
</div>

<form asp-page="./Index" asp-page-handler="Edit"
      method="post"
      data-ajax="true"
      data-callback=""
      data-action="Refresh"
      enctype="multipart/form-data">
    <div class="modal-body">
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="Name" class="control-label">نام</label>
                    <input type="text" class="form-control" asp-for="Name">
                    <span asp-validation-for="Name" class="error"></span>
                </div>
            </div><div class="col-md-6">
                <div class="form-group">
                    <label asp-for="Slug" class="control-label">اسلاگ</label>
                    <input type="text" class="form-control" asp-for="Slug">
                    <span asp-validation-for="Slug" class="error"></span>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <label asp-for="Picture" class="control-label">عکس</label>
                    <input type="text" class="form-control" asp-for="Picture">
                    <span asp-validation-for="Picture" class="error"></span>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="PictureAlt" class="control-label">Alt</label>
                    <input type="text" class="form-control" asp-for="PictureAlt">
                    <span asp-validation-for="PictureAlt" class="error"></span>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="PictureTitle" class="control-label">عنوان</label>
                    <input type="text" class="form-control" asp-for="PictureTitle">
                    <span asp-validation-for="PictureTitle" class="error"></span>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="form-group no-margin">
                    <label asp-for="Description" class="control-label">توضیحات</label>
                    <textarea class="form-control autogrow" asp-for="Description" onchange="fillField('Description', 'MetaDescription')"
                              style="overflow: hidden; word-wrap: break-word; resize: horizontal; height: 104px;"></textarea>
                    <span asp-validation-for="Description" class="error"></span>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <label asp-for="Keywords" class="control-label">کلمات کلیدی</label>
                    <input type="text" class="form-control" asp-for="Keywords">
                    <span asp-validation-for="Keywords" class="error"></span>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="form-group no-margin">
                    <label asp-for="MetaDescription" class="control-label">توضیحات متا</label>
                    <textarea class="form-control autogrow" asp-for="MetaDescription"
                              style="overflow: hidden; word-wrap: break-word; resize: horizontal; height: 104px;"></textarea>
                    <span asp-validation-for="MetaDescription" class="error"></span>
                </div>
            </div>
        </div>
        <input type="hidden" asp-for="Id" value="@Model.Id" />
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default waves-effect" data-dismiss="modal">بستن</button>
        <button type="submit" class="btn btn-info waves-effect waves-light">ویرایش</button>
    </div>
</form>

AriaSoleh.Co/ServiceHost/Areas/Administration/Pages/Shop/CompanyProjects/Index.cshtml
@page
@model ServiceHost.Areas.Administration.Pages.Shop.CompanyProjects.IndexModel
@{
}

@{
    Layout = "Shared/_AdminLayout";
    ViewData["title"] = "مدیریت پروژه ها ";
}

<div class="row">
    <div class="col-sm-12">
        <h4 class="page-title pull-right">@ViewData["title"]</h4>
        <p class="pull-left">
            <a class="btn btn-success btn-lg" href="#showmodal=@Url.Page("./Index", "Create")">ایجاد پروژه جدید</a>
        </p>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">جستجو در پروژ ها </h3>
            </div>
            <div class="panel-body">
                <form class="form-inline" role="form" method="get">
                    <div class="form-group">
                        <label class="sr-only" asp-for="SearchModel.Name"></label>
                        <input class="form-control" asp-for="SearchModel.Name" placeholder="نام گروه محصولی">
                    </div>
                    <button type="submit" class="btn btn-success waves-effect waves-light m-l-10">جستجو</button>
                    <a class="btn btn-primary waves-effect waves-light m-l-10" asp-page="./Index">مشاهده همه</a>
                </form>
            </div>
        </div>
    </div>
</div>

<div class="row" id="ProductCategoriesDiv">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">لیست پروژه ها</h3>
            </div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-md-12 col-sm-12 col-xs-12">
                        <table id="datatable" class="table table-striped table-bordered">
                            <thead>
                                <tr>
                                    <th>عکس</th>
                                    <th>نام</th>
                                    <th>تاریخ تولید</th>
                                    <th>عملیات</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model.CompanyProjects)
                                {
                                    <tr>
                                        <td>
                                            <img src="@item.Picture" style="width: 70px; height: 70px" />
                                        </td>
                                        <td>@item.Name</td>
                                        <td>@item.CreationDate</td>
                                        <td>
                                            <a class="btn btn-warning pull-right m-rl-5"
                                               href="#showmodal=@Url.Page("./Index", "Edit", new { @item.Id })">
                                                <i class="fa fa-edit"></i> ویرایش
                                            </a>
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script src="~/adminTheme/assets/datatables/jquery.dataTables.min.js"></script>
    <script src="~/adminTheme/assets/datatables/dataTables.bootstrap.js"></script>

    <script type="text/javascript">
        $(document).ready(function () {
            $('#datatable').dataTable();
        });
    </script>
}

AriaSoleh.Co/ServiceHost/Pages/Shared/ComingSoon.cshtml
@{
    Layout = null;
};
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="keywords" content="" />
    <meta name="author" content="" />
    <meta name="robots" content="" />
    <meta name="description" content="" />
    <meta property="og:title" content="Constructzilla - Construction Template" />
    <meta property="og:description" content="" />
    <meta property="og:image" content="" />
    <meta name="format-detection" content="telephone=no">

    <!-- FAVICONS ICON -->
    <link rel="icon" href="images/favicon.ico" type="image/x-icon" />
    <link rel="shortcut icon" type="image/x-icon" href="~/images/favicon.png" />

    <!-- PAGE TITLE HERE -->
    <title>Aria Soleh | Coming Soon</title>

    <!-- MOBILE SPECIFIC -->
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!--[if lt IE 9]>
    <script src="~/js/html5shiv.min.js"></script>
    <script src="~/js/respond.min.js"></script>
    <![endif]-->
    <!-- STYLESHEETS -->
    <link rel="stylesheet" type="text/css" href="~/css/plugins.css">
    <link rel="stylesheet" type="text/css" href="~/css/style.min.css">
    <link class="skin" rel="stylesheet" type="text/css" href="~/css/skin/skin-1.css">
    <link rel="stylesheet" type="text/css" href="~/css/templete.min.css">
    <link rel="stylesheet" type="text/css" href="~/css/style-rtl.css">



    <link rel="stylesheet" type="text/css" href="~/css/coming-soon.css">

</head>
<body id="bg">
    <div id="loading-area"></div>
    <div class="page-wraper boxed-full">
        <!-- Content -->
        <div class="blog-page-content style-1 sticky-header">
            <!-- Full Blog Page Contant -->
            <div id="particles-js" class="dez-coming-soon bg-img-fix dez-coming-soon-full  cs-style-1 p-b100 overlay-black-light" style="background-image:url(images/background/bg6.jpg);">
                <div class="container relative z-index2">
                    <div class="dez-coming-bx text-center f-ele-m" dez-top-pos="0">
                        <div class="top-head text-center logo-header">
                            <a>
                                <img src="~/images/logo-white-cu.png" alt="" />
                            </a>
                        </div>
                        <div class="coming-soon-content text-center text-white m-b30">
                            <h2 id="text">به زودی...، صبور باشید</h2>
                            <div class="countdown text-center">
                                <div class="date">
                                    <span class="secs text-primary time"></span>
                                    <span class="time-name">ثانیه</span>
                                </div>
                                <div class="date">
                                    <span class="mins text-primary time"></span>
                                    <span class="time-name">دقیقه</span>
                                </div>
                                <div class="date">
                                    <span class="hours text-primary time"></span>
                                    <span class="time-name">ساعت</span>
                                </div>
                                <div class="date">
                                    <span class="days text-primary time"></span>
                                    <span class="time-name">روز</span>
                                </div>
                            </div>
                            <p>شرکت سوله سازان طاهر آریا با بیش از 25 سال تجربه و اعتبار در ساخت انواع سازه های فلزی با بهره‌گیری از گروه مهندسان متخصص در امر مشاوره ، طراحی و ساخت انواع سوله سبک، صنعتی و … و در اختیار داشتن نیروی با تجربه در امر ساخت (مونتاژ و جوش) و همچنین برخورداری از سالن های مجزا و مجهز، با ظرفیت نامحدود تولید در حال فعالیت می باشد. کلیه مراحل تولید سازه های فلزی مطابق با آئین نامه های معتبر بین المللی و مقررات ملی ساختمان به انجام می رسد. این امر زیر نظر واحدهای کنترل کیفیت کارخانه صورت پذیرفته و برای کلیه پروژه ها و قطعات ساخته شده شناسنامه کیفی تهیه و پس از اتمام کار تحویل کارفرمایان محترم می شود. </p>
                            <p>
                                ________________________________________
                            </p>
                            <p><strong>شماره های تماس</strong></p>

                            <a href ="tel:+98913-151-7109"><strong>0913-151-7109</strong></a>
                            <p></p>
                            <a href="tel:+98913-671-1389"><strong>0913-671-1389</strong></a>
                            <p></p>
                            <a href="tel:+98035-3730-5707"><strong>035-3730-5707</strong></a>


                        </div>
                    </div>
                </div>
            </div>
            <!-- Full Blog Page Contant -->
        </div>
        <!-- Content END-->
    </div>
    <!-- JavaScript  files ========================================= -->
    <script src="~/js/jquery.min.js"></script><!-- JQUERY.MIN JS -->
    <script src="~/plugins/bootstrap/js/popper.min.js"></script><!-- BOOTSTRAP.MIN JS -->
    <script src="~/plugins/bootstrap/js/bootstrap.min.js"></script><!-- BOOTSTRAP.MIN JS -->
    <script src="~/plugins/countdown/jquery.countdown.js"></script><!-- JQUERY COUNTDOWN -->
    <script src="~/plugins/scroll/scrollbar.min.js"></script><!-- CUSTOM FUCTIONS  -->
    <script src="~/js/coming-soon.js"></script><!-- COMING SOON JS -->
    <script src='https://www.google.com/recaptcha/api.js'></script> <!-- Google API For Recaptcha  -->
    <script src="~/js/dz.ajax.js"></script><!-- CONTACT JS  -->

    <script src="~/plugins/particles/particles.js"></script><!-- PARTICLES  -->
    <script src="~/plugins/particles/particles.app.js"></script><!-- PARTICLES  -->

</body>
</html>

AriaSoleh.Co/ServiceHost/Pages/Shared/Components/CompanyProject/Default.cshtml
@model List<_01_Query.Contracts.CompanyProject.CompanyProjectQueryModel>

<div class="section-full bg-img-fix content-inner-1 overlay-black-middle" style="background-image:url(~/Theme/images/background/bg1.jpg);">
    <div class="container">
        <div class="section-head  text-center text-white">
            <h2 class="text-uppercase">پروژه های ما</h2>
            <div class="dez-separator-outer ">
                <div class="dez-separator bg-white style-skew"></div>
            </div>
            <p>به دلیل بهترین کیفیت و خدمات ، پیروزی همیشه هدف ما بوده است ، ما فقط بهترین استعدادها را به خاطر می آوریم. ما با راهنمایی ، سادگی و صداقت صحیح همه کارهایی را برای شما انجام خواهیم داد که بتواند شما را راحت کند.</p>
        </div>
        <div class="portfolio-carousel mfp-gallery gallery owl-carousel owl-btn-center-lr lightgallery">
            @foreach (var project in Model)
            {
                <div class="item">
                    <div class="ow-portfolio">
                        <div class="ow-portfolio-img dez-img-overlay1 dez-img-effect zoom-slow">
                            <img src="@project.Picture" alt="">
                            <div class="overlay-bx">
                                <div class="overlay-icon">
                                    <span data-exthumbimage="~/Theme/images/our-work/thumb/pic1.jpg" data-src="~/Theme/images/our-work/large/pic1.jpg" class="icon-bx-xs check-km" title="@project.Name">
                                        <i class="far fa-image"></i>
                                    </span>
                                    <a> <i class="fa fa-link icon-bx-xs"></i> </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            }
        </div>
    </div>
</div>